navbot_serial_bridge:
  ros__parameters:
    serial_port: /dev/serial/by-id/usb-Raspberry_Pi_Pico_E661410403114B35-if00
    baud_rate: 115200
    wheel_radius: 0.033
    wheel_separation: 0.180
    counts_per_revolution: 3945
    left_counts_per_revolution: 3943
    right_counts_per_revolution: 3946
    command_timeout: 0.5
    odom_frame: odom
    base_frame: base_footprint
    base_link_frame: base_link
    laser_frame: laser_link
    publish_tf: true
